# Generated by Django 4.2.2 on 2023-07-02 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('pan', models.CharField(max_length=16, unique=True)),
                ('expiry_date', models.DateField(blank=True)),
                ('cvv', models.CharField()),
                ('issue_date', models.DateField(blank=True)),
                ('owner_id', models.UUIDField(default=uuid.uuid4)),
                (
                    'status',
                    models.CharField(
                        choices=[('new', 'New'), ('active', 'Active'), ('blocked', 'Blocked')], default='new'
                    ),
                ),
            ],
        ),
    ]
