[tool.black]
include = '\.py$'
line-length = 120
skip-string-normalization = true

[tool.isort]
line_length = 120

[tool.pylint.main]
init-hook = 'import sys; sys.path.append(".")'
disable = [
    'invalid-name',
    'invalid-envvar-default',
    'line-too-long',
    'too-many-public-methods',
    'too-few-public-methods',
]
ignore-paths = [
    '^venv/.*$',
]
good-names = ['f', 's', 'x', 'n', 'i', 'j', 'k', 'ex', 'Run', '_']

[tool.pylint.format]
max-line-length = 120

[tool.pylint.variables]
init-import = 'no'

[tool.pylint.design]
max-branches = 1000
max-statements = 500

[tool.pylint.'messages control']
disable = [
    'missing-docstring',
    'empty-docstring'
]