from faker import Faker
from faker.providers import credit_card

faker = Faker()
faker.add_provider(credit_card)


def get_card_number():
    card_number = faker.credit_card_number()
    print(f'--> autogenerated pan as: {card_number}')
    return card_number


def get_card_cvv():
    cvv = faker.credit_card_security_code()
    print(f'--> autogenerated cvv as: {cvv}')
    return cvv


def get_name():
    name = faker.name()
    print(f'--> autogenerated name: {name}')
    return name
