# Generated by Django 4.2.2 on 2023-07-13 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('pan', models.CharField(max_length=16, unique=True)),
                ('expiry_date', models.DateField(blank=True)),
                ('cvv', models.CharField()),
                ('issue_date', models.DateField(blank=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('new', 'New'), ('active', 'Active'), ('blocked', 'Blocked')], default='new'
                    ),
                ),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                (
                    'owner',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
