# Generated by Django 4.2.2 on 2023-07-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0002_alter_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='printed_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
