# Generated by Django 4.2.2 on 2023-07-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0003_card_printed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(default='new'),
        ),
    ]
